/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jet_javafx_study_NativeTest */

#ifndef _Included_jet_javafx_study_NativeTest
#define _Included_jet_javafx_study_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jet_javafx_study_NativeTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jet_javafx_study_NativeTest_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
